// Generated by gencpp from file hrwros_msgs/boxHeightInformation.msg
// DO NOT EDIT!


#ifndef HRWROS_MSGS_MESSAGE_BOXHEIGHTINFORMATION_H
#define HRWROS_MSGS_MESSAGE_BOXHEIGHTINFORMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrwros_msgs
{
template <class ContainerAllocator>
struct boxHeightInformation_
{
  typedef boxHeightInformation_<ContainerAllocator> Type;

  boxHeightInformation_()
    : box_height(0.0)  {
    }
  boxHeightInformation_(const ContainerAllocator& _alloc)
    : box_height(0.0)  {
  (void)_alloc;
    }



   typedef float _box_height_type;
  _box_height_type box_height;





  typedef boost::shared_ptr< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> const> ConstPtr;

}; // struct boxHeightInformation_

typedef ::hrwros_msgs::boxHeightInformation_<std::allocator<void> > boxHeightInformation;

typedef boost::shared_ptr< ::hrwros_msgs::boxHeightInformation > boxHeightInformationPtr;
typedef boost::shared_ptr< ::hrwros_msgs::boxHeightInformation const> boxHeightInformationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrwros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/melodic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/melodic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/melodic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/melodic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'hrwros_msgs': ['/home/abu/hrwros_ws/src/hrwros/hrwros_msgs/msg', '/home/abu/hrwros_ws/devel/.private/hrwros_msgs/share/hrwros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b427ae616da4facf1fbfe9829db6b50";
  }

  static const char* value(const ::hrwros_msgs::boxHeightInformation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b427ae616da4facULL;
  static const uint64_t static_value2 = 0xf1fbfe9829db6b50ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrwros_msgs/boxHeightInformation";
  }

  static const char* value(const ::hrwros_msgs::boxHeightInformation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 box_height\n"
;
  }

  static const char* value(const ::hrwros_msgs::boxHeightInformation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct boxHeightInformation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrwros_msgs::boxHeightInformation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrwros_msgs::boxHeightInformation_<ContainerAllocator>& v)
  {
    s << indent << "box_height: ";
    Printer<float>::stream(s, indent + "  ", v.box_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRWROS_MSGS_MESSAGE_BOXHEIGHTINFORMATION_H
